fix/IT-7/filenames (#38)
Co-authored-by: Dzmitry Homza <dzmitry@beewise.ag>

diff --git a/.github/workflows/merge-sync.yml b/.github/workflows/merge-sync.yml
--- a/.github/workflows/merge-sync.yml
+++ b/.github/workflows/merge-sync.yml
@@ -184,20 +184,20 @@ jobs:
           if [[ "${{ github.ref_name }}" == "master" ]]; then
             echo "🚀 Merging master into release"
             git checkout release
-            git merge master --no-ff --no-commit || { echo "❌ Merge conflict in release"; git merge --abort; exit 1; }
+            git merge master --no-ff --no-commit || { echo "❌ Merge conflict detected! Aborting..."; git merge --abort; exit 1; }
             git commit -m "🔄 Back-merge master into release"
             git push origin release
 
             echo "🚀 Merging master into dev"
             git checkout dev
-            git merge master --no-ff --no-commit || { echo "❌ Merge conflict in dev"; git merge --abort; exit 1; }
+            git merge master --no-ff --no-commit || { echo "❌ Merge conflict detected! Aborting..."; git merge --abort; exit 1; }
             git commit -m "🔄 Back-merge master into dev"
             git push origin dev
 
           elif [[ "${{ github.ref_name }}" == "release" ]]; then
             echo "🚀 Merging release into dev"
             git checkout dev
-            git merge release --no-ff --no-commit || { echo "❌ Merge conflict in dev"; git merge --abort; exit 1; }
+            git merge release --no-ff --no-commit || { echo "❌ Merge conflict detected! Aborting..."; git merge --abort; exit 1; }
             git commit -m "🔄 Back-merge release into dev"
             git push origin dev
           else
